sudo: false
language: erlang
otp_release:
    - R16B02
    - R16B01
    - R16B
    - 17.0
    - 18.0

before_script:
    - hostname -f
    - cc -v
    - ld -v

before_script:
    - "wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3 && ./rebar3 local install"
    - "PATH=$PATH:~/.cache/rebar3/bin"

script:
    - "make travis"
